import Head from "next/head";

const Header = ()=>{
    return (
        <Head>
            <title>The Conquistador</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Header;